# Generated by Django 3.2 on 2021-04-09 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Atestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=30)),
                ('tipo_de_servico', models.CharField(max_length=30)),
                ('data_emissao', models.DateField(default=datetime.datetime.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.empresa')),
            ],
        ),
    ]
