# Generated by Django 3.2 on 2021-04-13 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Atestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=30)),
                ('tipo_de_servico', models.CharField(blank=True, choices=[('Desenvolvimento', 'Desenvolvimento'), ('ITS', 'ITS'), ('Service Desk', 'Service Desk'), ('Suporte', 'Suporte')], max_length=30)),
                ('data_emissao', models.DateField(default=datetime.datetime.now)),
                ('documento_pdf', models.FileField(upload_to='atestados/PDFs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_cliente', to='app.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_empresa', to='app.empresa')),
            ],
        ),
    ]
